{
 "title": "Sumario",
 "tags": [
  "atmos",
  "aire",
  "asturias",
  "contaminación",
  "biodevas"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Provincia",
    "label": "Área",
    "query": "select distinct region from registros;"
   },
   {
    "name": "estacion",
    "label": "Estación",
    "query": "select distinct city from registros WHERE region IN (${Provincia});"
   },
   {
    "name": "min_interval",
    "label": "intervalo",
    "query": "1h,6h,12h,1d,7d,14d,1m,3m,6m,1y"
   }
  ]
 },
 "panels": [
  {
   "title": "Índice de la calidad del aire",
   "type": "stat",
   "description": "https://aqicn.org/scale/",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(time,$__interval),\r\n  avg(aqi) AS \"aqi\"\r\nFROM registros\r\nWHERE\r\n  region IN ($Provincia) AND\r\n  city IN ($estacion) AND\r\n  $__timeFilter(time)\r\nGROUP by\r\n  city, time\r\nORDER by city asc, time desc"
    }
   ]
  },
  {
   "title": "Tendencia del índice de calidad del aire / Media ($min_interval)",
   "type": "timeseries",
   "description": "https://aqicn.org/scale/",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(aqi) AS \"aqi\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1, 2\nORDER BY 1, 2\n"
    }
   ]
  },
  {
   "title": "Histograma del índice de calidad del aire / Media ($min_interval)",
   "type": "histogram",
   "description": "https://aqicn.org/scale/",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(aqi) AS \"aqi\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP by\n  time, city"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": {
    "content": "# Info\n- Intervalo de recuperación de datos (variable): **$min_interval**\n- Fuente: https://waqi.info/"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gráficos de variables ambientales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperatura / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(t) AS \"Promedio\",\n  max(t) as \"Máximas\",\n  min(t) as \"Mínimas\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Humedad / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(h) AS \"Promedio\",\n  max(h) as \"Máximo\",\n  min(h) as \"Mínimo\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Presión atmosférica / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  avg(p) AS \"Promedio\",\n  max(p) as \"Máximo\",\n  min(p) as \"Mínimo\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  $__timeFilter(time)\nGROUP BY 1\nORDER BY 1\n\n"
    }
   ]
  },
  {
   "title": "Valores de contaminantes específicos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PM2.5 / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(pm25) AS \"pm25\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "PM10 / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(pm10) AS \"pm10\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "O3 / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(o3) AS \"o3\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "CO / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(co) AS \"co\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "NO2 / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(no2) AS \"no2\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "SO2 / Media ($min_interval)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  city AS metric,\n  avg(so2) AS \"so2\"\nFROM registros\nWHERE\n  region IN ($Provincia) AND\n  city IN ($estacion) AND\n  $__timeFilter(time)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}