{
 "title": "Vista de mapa",
 "tags": [
  "atmos",
  "aire",
  "asturias",
  "contaminación",
  "biodevas"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Provincia",
    "label": "Área",
    "query": "select distinct region from registros;"
   },
   {
    "name": "estacion",
    "label": "Estación",
    "query": "select distinct city from registros WHERE region IN (${Provincia});"
   }
  ]
 },
 "panels": [
  {
   "title": "Índice de la calidad del aire (Último)",
   "type": "stat",
   "description": "https://aqicn.org/scale/",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DISTINCT ON (city) city,\r\n  $__timeGroupAlias(time,$__interval),\r\n  avg(aqi)\r\nFROM registros\r\nWHERE\r\n  region IN ($Provincia) AND\r\n  city IN ($estacion) AND\r\n  $__timeFilter(time)\r\nGROUP by\r\n  city, time\r\nORDER by city asc, time desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 0 },
   "options": {
    "content": "# Información\n- Fuente: https://waqi.info/\n- Creado por: Jose Carlos Nieto Ramos"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Velocidad del viento",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DISTINCT ON (city) city,\r\n  $__timeGroupAlias(time,$__interval),\r\n  max(w) as \"wind\"\r\nFROM registros\r\nWHERE\r\n  region IN ($Provincia) AND\r\n  city IN ($estacion)\r\nGROUP by\r\n  city, time\r\nORDER by city asc, time desc"
    }
   ]
  },
  {
   "title": "Mapa de contaminación",
   "type": "geomap",
   "description": "https://aqicn.org/scale/",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  DISTINCT ON (city) city,\r\n  $__timeGroupAlias(time,$__interval),\r\n  aqi AS \"AQI\",\r\n  avg (co) AS \"co\",\r\n  avg (no2) AS \"no2\",\r\n  avg (o3) AS \"o3\",\r\n  avg (pm10) AS \"pm10\",\r\n  avg (pm25) AS \"pm25\",\r\n  avg (so2) AS \"so2\",\r\n  lat,\r\n  lon\r\nFROM registros\r\nWHERE\r\n  region IN ($Provincia) AND\r\n  city IN ($estacion)\r\nGROUP by\r\n  city, time, lat, lon, aqi\r\nORDER by city asc, time desc"
    }
   ]
  }
 ]
}